CREATE TABLE EMP_HW(
    EMPNO   NUMBER(4)
    , ENAME VARCHAR2(10)
    , JOB   VARCHAR2(9)
    , MGR   NUMBER(4)
    , HIREDATE  DATE
    , SAL   NUMBER(7,2)
    , COMM  NUMBER(7,2)
    , DEPTNO    NUMBER(2)
    );


ALTER TABLE EMP_HW
    ADD BIGO    VARCHAR2(20);

ALTER TABLE EMP_HW
    MODIFY BIGO VARCHAR2(30); 

ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;


DESC EMP_HW;