CREATE TABLE DEPT_HW
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_HW;

UPDATE DEPT_HW
SET DNAME = 'DATABASE'
    , LOC = 'SEOUL'
WHERE DEPTNO = 30;

SELECT * FROM DEPT_HW;

UPDATE DEPT_HW
SET DNAME = 'DATABASE'
    , LOC = 'SEOUL'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_HW;

commit;