-- 문제1
SELECT E.JOB
      , E.EMPNO
      , E.ENAME
      , E.SAL
      , E.DEPTNO
      , D.DNAME
FROM EMP E JOIN DEPT D
ON(E.DEPTNO = D.DEPTNO)
WHERE E.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');



-- 문제2
SELECT
    E.EMPNO
  , E.ENAME
  , D.DNAME
  , E.HIREDATE
  , D.LOC
  , E.SAL
  , S.GRADE
FROM EMP E
JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
JOIN SALGRADE S ON(E.SAL BETWEEN LOSAL AND HISAL)
WHERE E.SAL > (SELECT AVG(SAL)
                FROM EMP)
ORDER BY SAL DESC, E.EMPNO;



-- 문제3
SELECT
    E.EMPNO
  , E.ENAME
  , E.JOB
  , E.DEPTNO
  , D.DNAME
  , D.LOC
FROM EMP E
JOIN DEPT D
ON(E.DEPTNO = D.DEPTNO)
WHERE (E.DEPTNO, E.JOB) IN (SELECT DEPTNO, JOB
                          FROM EMP
                          WHERE DEPTNO = 10
                          AND JOB NOT IN ('SALESMAN','CLERK', 'MANAGER') )
;



-- 문제4
SELECT
      E.EMPNO
    , E.ENAME
    , E.SAL
    , S.GRADE
FROM EMP E
JOIN SALGRADE S
ON(E.SAL BETWEEN LOSAL AND HISAL)
WHERE E.SAL > (SELECT MAX(SAL)
                FROM EMP
                WHERE JOB = 'SALESMAN')
ORDER BY EMPNO;


SELECT SAL
FROM EMP
WHERE JOB = 'SALESMAN'
ORDER BY SAL DESC;

SELECT
      E.EMPNO
    , E.ENAME
    , E.SAL
    , S.GRADE
FROM EMP E
JOIN SALGRADE S
ON(E.SAL BETWEEN LOSAL AND HISAL)
WHERE E.SAL > ALL (SELECT SAL
                    FROM EMP
                    WHERE JOB = 'SALESMAN')
ORDER BY EMPNO;