
CREATE TABLE CHAP10HW_EMP
    AS SELECT * FROM EMP;

CREATE TABLE CHAP10HW_DEPT
    AS SELECT * FROM DEPT;

CREATE TABLE CHAP10HW_SALGRADE
    AS SELECT * FROM SALGRADE;

SELECT * FROM CHAP10HW_EMP;

-- 문제1
INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
        VALUES (50,'ORACLE','BUSAN');

INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)        
        VALUES(60,'SQL','ILSAN');

INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
        VALUES(70,'SELECT','INCHEON');

INSERT INTO CHAP10HW_DEPT(DEPTNO, DNAME, LOC)
        VALUES(80,'DML','BUNDANG');
    



-- 문제2
INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('16/01/02','YY/MM/DD'), 4500, NULL, 50);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('16/02/21','YY/MM/DD'), 1800, NULL, 50);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7203, 'TEST_USER3', 'ANALIST', 7201, TO_DATE('16/04/11','YY/MM/DD'), 3400, NULL, 60);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('16/05/31','YY/MM/DD'), 2700, 300, 60);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('16/07/20','YY/MM/DD'), 2600, NULL, 70);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('16/09/08','YY/MM/DD'), 2600, NULL, 70);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('16/10/28','YY/MM/DD'), 2300, NULL, 80);

INSERT INTO CHAP10HW_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('18/03/09','YY/MM/DD'), 1200, NULL, 80);

SELECT * FROM CHAP10HW_EMP;

-- 문제3
SELECT AVG(SAL) FROM CHAP10HW_EMP
WHERE DEPTNO = 50;

UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
                FROM CHAP10HW_EMP
                WHERE DEPTNO = 50);

SELECT * FROM CHAP10HW_EMP;

-- 문제4
SELECT ENAME, MAX(HIREDATE) FROM CHAP10HW_EMP
WHERE DEPTNO = 60
GROUP BY ENAME;

SELECT ENAME, HIREDATE FROM CHAP10HW_EMP    /*급여 10%인상 후 80번 부서로 이동*/
WHERE HIREDATE > (SELECT MAX(HIREDATE)
                    FROM CHAP10HW_EMP
                    WHERE DEPTNO = 60
                 ); 

UPDATE CHAP10HW_EMP
SET SAL = (SAL * 1.1)
    ,DEPTNO = 80
WHERE HIREDATE > (SELECT MAX(HIREDATE)
                    FROM CHAP10HW_EMP
                    WHERE DEPTNO = 60);

SELECT * FROM CHAP10HW_EMP
ORDER BY DEPTNO;

-- 문제5
SELECT E.SAL
FROM CHAP10HW_EMP E
JOIN CHAP10HW_SALGRADE S
ON(E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE S.GRADE = 5;

DELETE FROM CHAP10HW_EMP
    WHERE SAL IN (SELECT E.SAL
                    FROM CHAP10HW_EMP E
                    JOIN CHAP10HW_SALGRADE S
                    ON(E.SAL BETWEEN S.LOSAL AND S.HISAL)
                    WHERE S.GRADE = 5);

SELECT * FROM CHAP10HW_EMP;

COMMIT;

SELECT * FROM CHAP10HW_EMP;
