-- 과제
-- 문제1
SELECT
  EMPNO
, RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS "MASKING_EMPNO"
, ENAME
, RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS "MASKING_ENAME"
FROM EMP
WHERE LENGTH(ENAME) >= 5
AND LENGTH(ENAME) < 6;

-- 문제2
SELECT
      EMPNO
    , ENAME
    , SAL
    , TRUNC(SAL/21.5,2) AS "DAY_PAY"
    , ROUND((TRUNC(SAL/21.5,2)/8),1) AS "TIME_PAY"
FROM EMP;

-- 문제3
SELECT 
      EMPNO
    , ENAME
    , TO_CHAR(HIREDATE,'YYYY-MM-DD')
    , NEXT_DAY(ADD_MONTHS(HIREDATE,3),'월') AS "R_JOB" /*사원이 정직원이 되는 날짜(입사일 기준 3개월 뒤의 첫 월요일*/
    , CASE /*추가수당 없는 사원의 추가수당 = N/A 로 출력*/
        WHEN COMM IS NULL THEN 'N/A'
        ELSE ''||COMM
        END AS COMM
FROM EMP;  

-- 문제4
SELECT
    EMPNO
  , ENAME
  , MGR /*직속상관의 사원번호*/
  , CASE
      WHEN MGR IS NULL THEN '0000'
      WHEN SUBSTR(MGR,1,2) = 75 THEN '5555'
      WHEN SUBSTR(MGR,1,2) = 76 THEN '6666'
      WHEN SUBSTR(MGR,1,2) = 77 THEN '7777'
      WHEN SUBSTR(MGR,1,2) = 78 THEN '8888'
      ELSE ''||MGR
      END AS CHG_MGR /*조건 적용 시*/
FROM EMP;

-- 문제5
SELECT
    DEPTNO
  , TRUNC(AVG(SAL)) AS AVG_SAL
  , TRUNC(MAX(SAL)) AS MAX_SAL
  , TRUNC(MIN(SAL)) AS MIN_SAL
  , COUNT(ENAME) AS CNT
FROM EMP
GROUP BY DEPTNO
;

-- 문제6
SELECT
   JOB
  , COUNT(JOB)
FROM EMP
GROUP BY JOB
  HAVING COUNT(JOB) >= 3
  ;  

-- 문제7
SELECT
    TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR
  , DEPTNO
  , COUNT(HIREDATE) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), DEPTNO
;

-- 문제8
SELECT
    NVL2(COMM,'O','X') AS EXIST_COMM
  , COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X')
;
