/*dept_const 테이블과 emp_const 테이블을 다음과 같은 특성과 제약 조건을 지정하여 만들기.*/

CREATE TABLE DEPT_CONST (
      DEPTNO   NUMBER(2)   CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY
    , DNAME    VARCHAR2(14)    CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE
    , LOC      VARCHAR2(13)    CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);

DESC DEPT_CONST;


CREATE TABLE EMP_CONST (
      EMPNO     NUMBER(4)    CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY
    , ENAME     VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL
    , JOB       VARCHAR2(9)   
    , TEL       VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE
    , HIREDATE  DATE
    , SAL       NUMBER(7,2)  CONSTRAINT EMPCONST_SAL_CHK CHECK(SAL BETWEEN 1000 AND 9999)
    , COMM      NUMBER(7,2)
    , DEPTNO    NUMBER(2)    CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST (DEPTNO)
);

DESC EMP_CONST;

COMMIT;


SELECT
    E.*
  , D.*
FROM EMP_CONST E, DEPT_CONST D
WHERE E.DEPTNO = D.DEPTNO;

CREATE VIEW VW_CONST
  AS (SELECT
        E.*
      , D.DNAME
      , D.LOC
      FROM EMP_CONST E, DEPT_CONST D
      WHERE E.DEPTNO = D.DEPTNO);

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPT_CONST', 'EMP_CONST')
ORDER BY TABLE_NAME, CONSTRAINT_NAME;




