/*OTT 종류 테이블========================================================================*/
CREATE TABLE OTTLIST(
    NO          NUMBER(5)
    , OTT_NAME  VARCHAR2(20)
    );

INSERT INTO OTTLIST (NO, OTT_NAME, CASH) 
VALUES (10, 'Netflix', 30000);

INSERT INTO OTTLIST (NO, OTT_NAME, CASH) 
VALUES (20, 'disneyplus', 20000);

INSERT INTO OTTLIST (NO, OTT_NAME, CASH) 
VALUES (30, 'tving', 25000);

SELECT * FROM OTTLIST;



ALTER TABLE OTTLIST
    MODIFY (OTT_NAME NOT NULL);

ALTER TABLE OTTLIST
    MODIFY (NO NOT NULL);

alter table OTTLIST
    add(CASH NUMBER(5));

ALTER TABLE OTTLIST
    MODIFY (CASH NOT NULL);

DESC OTTLIST;


/*유저 정보 테이블 ========================================================================*/
CREATE TABLE OTTUSER(
    USERID      NUMBER(5) CONSTRAINT USER_TABLE_PK PRIMARY KEY
    , USERNAME  VARCHAR2(10) CONSTRAINT USER_TABLE_NN NOT NULL
    );

alter table OTTUSER
    add(ROOM_NO NUMBER(5));


INSERT INTO OTTUSER (USERID, USERNAME, ROOM_NO)
VALUES (001, 'KING', NULL);

INSERT INTO OTTUSER (USERID, USERNAME, ROOM_NO)
VALUES (002, 'KOKO', NULL);

INSERT INTO OTTUSER (USERID, USERNAME, ROOM_NO)
VALUES (003, 'JOJO', NULL);

UPDATE OTTUSER
 SET ROOM_NO = 1
WHERE USERNAME ='KING';

SELECT * FROM OTTUSER;


/*웨이팅 상태 유저 테이블========================================================================*/
CREATE TABLE OTT_WATING(
    WATING_USERID   NUMBER(5) CONSTRAINT WATING_TABLE_FK REFERENCES OTTUSER (USERID)
    , ROOM_NO       NUMBER(5) 
    , LIDER         VARCHAR2(10)
);

alter table OTT_WATING
    add(OTT_NO NUMBER(5));


INSERT INTO OTT_WATING (WATING_USERID, ROOM_NO, LIDER, OTT_NO)
VALUES (002, 1, 'KING',10);

INSERT INTO OTT_WATING (WATING_USERID, ROOM_NO, LIDER, OTT_NO)
VALUES (003, 1, 'KING',10);

INSERT INTO OTT_WATING (WATING_USERID, ROOM_NO, LIDER,OTT_NO)
VALUES (001, 2, 'KOKO',20);



/*JOIN 결과 테스트========================================================================*/

SELECT
W.ROOM_NO
, W.LIDER
, L.OTT_NAME
, COUNT(W.WATING_USERID) AS COUNT
, L.CASH/COUNT(W.WATING_USERID) AS SHARE_CASH
FROM OTTLIST L, OTTUSER U, OTT_WATING W
WHERE W.WATING_USERID = U.USERID
AND W.OTT_NO = L.NO
GROUP BY W.ROOM_NO, W.LIDER, L.OTT_NAME, L.CASH;
